select	client_name,
		STATUS,
		CONSUMER_GROUP,
		PRIORITY_OVERRIDE,
		RESOURCE_PERCENTAGE,
		MEAN_JOB_DURATION,
		MEAN_JOB_CPU,
		MAX_DURATION_LAST_7_DAYS,
		MAX_DURATION_LAST_30_DAYS
from dba_autotask_client
/